@host = http://localhost
@port = 5268

@Restaurant.API_HostAddress = https://localhost:7058

GET {{Restaurant.API_HostAddress}}/api/restaurants

###

@id=0
GET {{Restaurant.API_HostAddress}}/api/restaurants/4

###

POST {{Restaurant.API_HostAddress}}/api/restaurants
Content-Type: application/json
{
  "Name" : "Mang Inasal",
  "Description" : "A Filipino Restaurant",
  "Category" : "Italiadn",
  "HasDelivery" : true,
  "ContactEmail" : "MangInasal@gmail.com",
  "ConctactNumber" : "01293213",
  "City" : "Davao",
  "Street" : "456 boulkevard",
  "PostalCode" : "02-800"
}

###

DELETE {{Restaurant.API_HostAddress}}/api/restaurants/5

###

PATCH {{Restaurant.API_HostAddress}}/api/restaurants/4
Content-Type: application/json

{
    "Name" : "Mang Inasal123",
    "Description" : "A Filipino Restaurant123",
    "HasDelivery" : true
}

###
